### ISSUE TITLE
Need to plug logic analyzer

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/Paperino-tests#1]
@RobPo I might start the other way around with this. Just making a fork of your original library and making it work for Arduino- esp32

Then at least I could have a good reference to do the ESP-IDF library. Otherwise it's hard to have a working model.

Things I've noticed from first tests: 

 - CPU speed > 80 Mhz makes the library stop working correctly. It sends the buffer and does a refresh but nothing comes (Or does but shifted(
 - Adding a delayMicroseconds(180); in the buffer loop after each SPI byte sent partly solves this (But should not be like that)

So maybe is a good idea to have a working ESP32 version that you can later merge after testing and then kick start the IDF class for my component

**Comment by RobPo** [comment]
Hmm, two thoughts: 
- SPI speed should not be faster than 6Mhz
- The busy GPIO indicates if the driver IC is ready for reading new commands/data. Maybe the function checkforBusyInactive(); needs to be inserted now somewhere else due to the higher CPU clock.

Please can you specify the exact location where the delayMicroseconds() is inserted; and/or try to replace it with waitforBusyInactive();?

**Comment by martinberlin** [comment]
Sure needs to be here in the [writeBuffer() method](https://github.com/RobPo/Paperino/blob/maste/src/PL_microEPD.cpp#L378).

Something around this I tried:

delayMicroseconds(180);

This is loop is not a good place to put a wait for busy. In other commands make sense but not when you are sending the pixel data buffer.
SPI speed is 4 Mhz in my component as default. This weekend I will debug it with a logic analyzer.
After somedays it will start working, will be a nice fight since is a new kind of IC controller for me, that I never used before. Thanks a lot for sending this two samples.

**Comment by martinberlin** [comment]
Is working and both 1.1 and 1.4 passed all tests
